# Setup
title:               jmKanz.io
tagline:             'Kube Padwan and Cloud Engineer'
description:         'jmKanz.io'
url:                 https://jmkanz.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Justin Kanz
  url:               https://www.github.com
  email:             justinkanz@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
